task: "detect" # Could be 'detect', 'segment', or 'pose'
mode: predict
augment: True # apply augment to train
model_path: models/detect/train/best.pt      # If provided, load and use this model
save_model_path: "models/pose/train/exp1.pt"  # Where to save the model (only used in training)
model_size: "n" # Can be: 'n', 's', 'm', 'l', 'x'
data: 

# Train settings
train:
  epochs: 2
  patience: 50
  batch: 5
  imgsz: 640
  save: True
  cache: False
  workers: 8
  pretrained: True
  optimizer: auto
  verbose: True
  seed: 0
  deterministic: True
  single_cls: False
  rect: False
  cos_lr: False
  close_mosaic: 10
  resume: False
  plots: True
  save_dir: "log_results"
  project:
  name: 
  save_txt: False
  conf:  0.001 # (float, optional) object confidence threshold for detection (default 0.25 predict, 0.001 val)
  plots: True 
  half: False  # (bool) use half precision (FP16)
  save_hybrid: False  # (bool) save hybrid version of labels (labels + additional predictions)
  iou: 0.7
  max_det: 300  # (int) maximum number of detections per image
  save_json: False  # (bool) save results to JSON file
  mask_ratio: 4


# Prediction
predict:
  source: "test_predict\\bus.jpg" 
  augment: False
  agnostic_nms: False
  classes:  # (int | list[int], optional) 
  boxes: True
  show: True
  conf: 0.25
  visualize: True  # (bool) visualize model features
  save_txt: True
  save: True
  boxes: True 
  line_width: 
  show_conf: True
  show_labels: True 
  retina_masks: False 
  save_conf: False 
  save_crop: False
  project:
  name: 'predict_results'
  verbose:
  iou: 0.7  # (float) intersection over union (IoU) threshold for NMS
  max_det: 300 



# Hyperparameters
hyperparameters:
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  dfl: 1.5
  pose: 12.0
  kobj: 1.0
  nbs: 64
  overlap_mask: True

# Augmentation settings
augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  imgsz: 640
  copy_paste: 0.0 
  mask_ratio: 4 
  overlap_mask: True

# Transform COCO to YOLO dataset 
dataset_config:
  coco_dataset_path: "coco_dataset"
  coco_ann_path: "annotations"
  ann_paths:
    detect: "instances_val2017.json"
    segment: "instances_val2017.json"
    pose: "person_keypoints_val2017.json"
  img_dir: "images"
  out_dir: "yolo_dataset"
  max_images: 500
  train_ratio: 0.8